# Pipeline to make automated tests
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '12.x'

- bash: |
    sudo apt install -y \
      build-essential \
      autoconf \
      automake
  displayName: 'Setup packages'

- bash: 'sudo apt remove libgmp-dev'
  displayName: 'Removing the original GMP'

- bash: |
    aclocal
    automake --foreign
    autoconf
  displayName: 'Preparation'

- bash: './configure --disable-shared --disable--assembly --host=amd64'
  displayName: 'Configuration'

- bash: |
    make
    make install
  displayName: 'Make GMP'

- bash: 'git clone https://github.com/cryptid-org/cryptid-native.git'
  displayName: 'Cloning cryptid-native'

- bash: |
    cd cryptid-native/
    ./task.sh test
  displayName: 'Running tests'